# Import from the submodule, never the package: this file runs first, so the package is still incomplete.
# The marker ops are re-exported because saved graphs name them as ``pytensor_ml.layers.<Op>``.
from pytensor_ml.base import Layer
from pytensor_ml.layers.attention import (
    AttentionLayer,
    CausalSelfAttention,
    MultiheadAttention,
    scaled_dot_product_attention,
)
from pytensor_ml.layers.combinators import (
    Concatenate,
    Flatten,
    Input,
    Sequential,
    Squeeze,
)
from pytensor_ml.layers.conv import (
    AvgPool1D,
    AvgPool2D,
    Conv1D,
    Conv2D,
    ConvLayer,
    ConvTranspose1D,
    ConvTranspose2D,
    MaxPool1D,
    MaxPool2D,
    PoolLayer,
    PoolLayerGrad,
    Upsample1D,
    Upsample2D,
)
from pytensor_ml.layers.dropout import Dropout, DropoutLayer
from pytensor_ml.layers.embedding import Embedding, EmbeddingLayer
from pytensor_ml.layers.linear import Linear, LinearLayer
from pytensor_ml.layers.norm import (
    BatchNorm,
    BatchNormLayer,
    GroupNorm,
    GroupNormLayer,
    LayerNorm,
    LayerNormLayer,
    NoRunningStatsBatchNormLayer,
    PredictionBatchNormLayer,
    RMSNorm,
    RMSNormLayer,
)
from pytensor_ml.layers.padding import (
    ConstantPad1D,
    ConstantPad2D,
    ReflectionPad1D,
    ReflectionPad2D,
    ReplicationPad1D,
    ReplicationPad2D,
    ZeroPad1D,
    ZeroPad2D,
)
from pytensor_ml.layers.positional import RotaryEmbedding, RotaryEmbeddingLayer, rotary_embedding
from pytensor_ml.layers.recurrent import (
    GRU,
    LSTM,
    RNN,
    Bidirectional,
    ElmanCell,
    GRUCell,
    LSTMCell,
    Recurrent,
    RecurrentCell,
)
from pytensor_ml.layers.transformer import FeedForward, TransformerBlock

__all__ = [
    "GRU",
    "LSTM",
    "RNN",
    "AvgPool1D",
    "AvgPool2D",
    "BatchNorm",
    "Bidirectional",
    "CausalSelfAttention",
    "Concatenate",
    "ConstantPad1D",
    "ConstantPad2D",
    "Conv1D",
    "Conv2D",
    "ConvLayer",
    "ConvTranspose1D",
    "ConvTranspose2D",
    "Dropout",
    "ElmanCell",
    "Embedding",
    "FeedForward",
    "Flatten",
    "GRUCell",
    "GroupNorm",
    "Input",
    "LSTMCell",
    "Layer",
    "LayerNorm",
    "Linear",
    "MaxPool1D",
    "MaxPool2D",
    "MultiheadAttention",
    "PoolLayer",
    "PoolLayerGrad",
    "RMSNorm",
    "Recurrent",
    "RecurrentCell",
    "ReflectionPad1D",
    "ReflectionPad2D",
    "ReplicationPad1D",
    "ReplicationPad2D",
    "RotaryEmbedding",
    "Sequential",
    "Squeeze",
    "TransformerBlock",
    "Upsample1D",
    "Upsample2D",
    "ZeroPad1D",
    "ZeroPad2D",
    "rotary_embedding",
    "scaled_dot_product_attention",
]
