name: mypy

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - ".github/workflows/mypy.yml"
      - "pytensor_ml/**"
      - "scripts/run_mypy.py"
      - "pyproject.toml"
      - "pixi.lock"

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
      with:
        environments: lint
        cache: true

    - name: Run mypy
      run: pixi run -e lint mypy
